### PR TITLE
docs: template installation command fix

### PR DESCRIPTION
**Pull request by anddrzejb**
Had an issue with off-the-shelf instruction, so here is the really small fix that may help someone.

### CODE REVIEW

**Comment by ElderJames** [comment]
Thank you, it seems that should fix the template config.

**Comment by anddrzejb** [comment]
There is still a problem with template. For example for server/client full it gets AntDesign version 0.5.0-* instead of 0.6.0-* (I think it is the file `.template.config\templates\hosted\src\Client\AntDesign.Pro.Template.Client.csproj` but this is first time I am trying something with templates and in my dev machine it does not event compile...). I think this is the reason why my PR as well as #52 are failing at build stage...

**Comment by ElderJames** [comment]
Exactly. It only compile while you create a template through install it...

**Comment by ElderJames** [comment]
Exactly. It only compile while you create a template through install it...

**Comment by anddrzejb** [comment]
I am not sure if we are on the same page. You noticed that my PR is changing only the `README.md`, right?

**Comment by anddrzejb** [comment]
@ElderJames commit 84e696d should fix the build error.

**Review by ElderJames — APPROVED** [review]
Thank you!

**Pull request merged**
